class DIB_Header
{
	char header[124];
	int header_size;
	int image_width;
	int image_height;
	int number_of_planes;
	int bits_per_pixel;
	int compression_method;
	int pixel_array_size;
	int pixel_per_meter_h;
	int pixel_per_meter_v;
	int number_of_colors;
	int number_of_imp_colors;
	public: DIB_Header();
		DIB_Header(const char *filename); 
		int get_header_size();
		void set_header_size(int hs);
		int get_image_width();
		void set_image_width(int iw);
		int get_image_height();
		void set_image_height(int ih);
		int get_number_of_planes();
		void set_number_of_planes(int nop);
		int get_bits_per_pixel();
		void set_bits_per_pixel(int bpp);
		int get_compression_method();
		void set_compression_method(int cm);
		int get_pixel_array_size();
		void set_pixel_array_size(int pas);
		int get_pixel_per_meter_h();
		void set_pixel_per_meter_h(int ppmh);
		int get_pixel_per_meter_v();
		void set_pixel_per_meter_v(int ppmv);
		int get_number_of_colors();
		void set_number_of_colors(int noc);
		int get_number_of_imp_colors();
		void set_number_of_imp_colors(int noic);
		void copy_DIB_Header(char *destination);
		void display_DIB_Header();
};
